# Site settings
title: "Jekyll Resume"
description: "Łukasz Bożek resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Łukasz Bożek"
resume_title:                   "iOS Developer"
resume_contact_email:           "bozek.lu@gmail.com"
# resume_contact_telephone:       ""
resume_contact_address:         "Poznań"
resume_header_contact_info: "bozek.lu@gmail.com"
resume_header_intro: "<p>To work in learning and challenging environment, utilizing my skill and knowledge to be the best of my abilities and contribute positively to my personal growth as well as growth of the organization.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/bozek-lu"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/bozek-lu"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "https://stackoverflow.com/users/4687211/lu"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
